### PR TITLE
Add cheat sheet

### PR DESCRIPTION
**Pull request by zoltanbedi**
I'm not sure if this change is going to broke something or not. It seems to work for me. I'm only saying this because I removed the useInitquery hook.

### CODE REVIEW

**Comment by zoltanbedi** [comment]
What's up with codeclimate? Is this something we want?

**Comment by aocenas** [comment]
Hmm no idea about the codeclimate, we can probably remove it, don't think the errors there are useful either.

**Comment by aocenas** [comment]
Looks good there are just 2 things:
1. right now you cannot run the initial query, probably because it is empty and there is a check somewhere. Ie if I am here:
Screenshot from 2020-09-17 12-14-40

if I click Run query nothing happens.

2. Small nitpick but lets remove the <td> padding in the table so the columns are aligned with the titles a bit better:
Screenshot from 2020-09-17 12-13-06

**Comment by aocenas** [comment]
@zoltanbedi so did not find any good solution for this tbh. At this moment lets just put the query init code back, so you can run the query explicitly and add an icon into the query field label with link to https://docs.aws.amazon.com/xray/latest/devguide/xray-console-filters.html?icmpid=docs_xray_console, something like this:
Screenshot from 2020-09-19 15-36-51

**Comment by aocenas** [comment]
@zoltanbedi I did some small changes hope that's ok.
- Moved the link to the docs inside the tooltip content. I don't think we have the info icon clickable anywhere so I think this is a bit easier to discover.
- Added the cheat sheet again. I did not mean us to remove it all just the initialisation change. I know it won't show anywhere but once we fix it in Grafana we don't have to do another PR to add it again.

**Comment by zoltanbedi** [comment]
@aocenas Got it. Sounds good to me.

**Pull request merged**
