### PR TITLE
Group selector implementation

### PR DESCRIPTION
**Pull request by aocenas**
Add group selector in query editor and implement filtering based on that.
Screenshot from 2020-09-02 13-40-21

### CODE REVIEW

**Comment by zoltanbedi** [comment]
This looks good altough I see an error like this in the grafana console the first time open explore with x-ray data source selected.
```
EROR[09-02|15:20:23] Metric request error                     logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Canceled desc = context canceled" remote_addr=[::1]
```

**Comment by aocenas** [comment]
@zoltanbedi Seems like the error is just normal cancellation. There isn't a check what kind of error is returned from the data source and all are then logged as error and returned as 500 even cancellations.

Question is why we are doing 2 requests on refresh (first one is cancelled). I would guess again some issue in the redux actions and the explore bootstraping logic. This happens also with other data sources so does not seem like something we could affect from here.

**Comment by zoltanbedi** [comment]
I think it is ok then

**Comment by zoltanbedi** [comment]
One thing that is missing the all option for insights but I can add that in a different pr and we can merge this.

**Review by zoltanbedi — APPROVED** [review]

**Comment by aocenas** [comment]
> One thing that is missing the all option for insights but I can add that in a different pr and we can merge this.

Ah sorry missed that comment. Yeah that would be cool.

**Pull request merged**
