### PR TITLE
Add All option to groups when insights selected

### PR DESCRIPTION
**Pull request by zoltanbedi**
- All option added to groups when insights query type is selected
- Added state column to table
- Changed duration column to be string type

### CODE REVIEW

**Comment by aocenas** [comment]
Seems like this broke the duration formatting:
Screenshot from 2020-09-08 15-18-40

Also can we make the All option the first in the list similar to how it is in x-ray?
Screenshot from 2020-09-08 15-18-49

**Comment by zoltanbedi** [comment]
Should be good now. The duration is fixed in latest master.

**Comment by aocenas** [comment]
Seems like I am getting a panic in go now:
```
BUG[09-09|11:33:54] panic: runtime error: invalid memory address or nil pointer dereference logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdc2d81] logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54]                                          logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54] goroutine 104 [running]:                 logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54] github.com/grafana/x-ray-datasource/pkg/datasource.getInsightSummary(0x135ad40, 0xc003c1a070, 0x1888881, 0x1, 0xc003c00260, 0xb, 0x48f, 0x1a3185c5000, 0xd59f80, 0xed6c30b82, ...) logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54] 	/home/andrej/dev/x-ray-datasource/pkg/datasource/getInsights.go:125 +0x9a1 logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54] github.com/grafana/x-ray-datasource/pkg/datasource.getSingleInsight(0x135ad40, 0xc003c1a070, 0x1888881, 0x1, 0xc003c00260, 0xb, 0x48f, 0x1a3185c5000, 0xd59f80, 0xed6c30b82, ...) logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54] 	/home/andrej/dev/x-ray-datasource/pkg/datasource/getInsights.go:89 +0x10e5 logger=plugins.backend pluginId=grafana-x-ray-datasource
DBUG[09-09|11:33:54] github.com/grafana/x-ray-datasource/pkg/datasource.(*Datasource).getInsights(0xc0003b83c0, 0x1358dc0, 0xc0028fe870, 0xc003c08a00, 0x0, 0x0, 0x0) logger=plugins.backend pluginId=grafana-x-ray-datasource

```

with query:
```
DBUG[09-09|11:36:02] Processing metrics query                 logger=http.server query="&{data:map[datasourceId:20 group:map[FilterExpression:service(\"Grafana XRay\") GroupARN:arn:aws:xray:us-west-2:489433021176:group/Grafana/VPVF47MXMEGF3K7AD5RKMS65GT7QDVAXV4DGHWTMGBNASOA3SR7A GroupName:Grafana InsightsConfigurationSummary:<nil>] intervalMs:1800000 key:Q-b0593ad2-4519-4559-aca6-50c69016b551-0 maxDataPoints:1167 orgId:1 query:service(\"Grafana XRay\") queryType:getInsights refId:A]}"
```

Can you check that I seem to be on latest master and latest commit of this PR.

**Comment by zoltanbedi** [comment]
This is paniced because EndTime was nil. It was failing at the moment of querying 😱
Good thing that happened because it revealed that bug that I didn't handle it properly. Added a test case for this and also some minor tweaks. Show categories in table, convert categories and state to Title case, show whole summery when endtime is nil.

**Comment by aocenas** [comment]
So basically that is a case an incident is in progress and it's not closed yet right?

**Comment by zoltanbedi** [comment]
> So basically that is a case an incident is in progress and it's not closed yet right?

correct

**Review by aocenas — APPROVED** [review]
Nice, looks like this works fine now.

**Pull request merged**
